// <auto-generated />
using System;
using Flipbook_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flipbook_App.Migrations
{
    [DbContext(typeof(FlipbookDBContext))]
    [Migration("20250904051221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("FlipBook_App.Shared.Core.AnimationReference", b =>
                {
                    b.Property<Guid>("AnimationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimationID");

                    b.HasIndex("UserID", "Title")
                        .IsUnique();

                    b.ToTable("Animations");
                });

            modelBuilder.Entity("FlipBook_Library.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlipBook_App.Shared.Core.AnimationReference", b =>
                {
                    b.HasOne("FlipBook_Library.Core.User", "User")
                        .WithMany("Animations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlipBook_Library.Core.User", b =>
                {
                    b.Navigation("Animations");
                });
#pragma warning restore 612, 618
        }
    }
}
